services:

  mysql:
    image: mysql:8.3
    container_name: person-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springboot_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    image: person-api:1.0
    container_name: person-api
    depends_on:
      - mysql
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/springboot_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  web:
    image: person-web:1.0
    container_name: person-web
    depends_on:
      - api
    ports:
      - "8080:8080"

  jenkins:
    image: jenkins/jenkins:lts
    container_name: person-jenkins
    ports:
      - "8081:8080"
    volumes:
      - jenkins_data:/var/jenkins_home

volumes:
  mysql_data:
  jenkins_data:
